spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jdbc:
    template:
      fetch-size: 50
      query-timeout: 30
server:
  port: 8080
